### ISSUE TITLE
Support new compliance groups HIPAA and NIST 800 53

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-splunk#705]
This issue is related to:
* https://github.com/wazuh/wazuh-api/issues/386

App must consider new groups that are being added to the ruleset:
* hipaa
* nist-800-53

**Comment by jesusgn90** [comment]
**Proposal**

- Two new dashboards for both HIPAA and NIST-800-53 as well, under _Regulatory Compliance_
  - Overview, Agents

**Comment by pablotr9** [comment]
Working on this branch: https://github.com/wazuh/wazuh-splunk/tree/hipaa-nist
 - HIPAA and NIST 800-53 have been added as extensions:
![image](https://user-images.githubusercontent.com/35685689/58553064-2ef0ca80-8214-11e9-9f75-db1d30c9b3cf.png)

 - Both extensions have been added to Overview -> Regulatory Compliance:
![image](https://user-images.githubusercontent.com/35685689/58553176-855e0900-8214-11e9-99f1-ec7f3e6fdddd.png)

 - They have also been added to Agents -> Regulatory Compliance:
![image](https://user-images.githubusercontent.com/35685689/58553218-a888b880-8214-11e9-8273-6c265cad40c2.png)
Currently HIPAA and NIST 800-53 dashboards are empty until Wazuh API adds calls for these new extensions.
 - We can now filter by these two new extensions at Management -> Rules search filter bar:
![image](https://user-images.githubusercontent.com/35685689/58553547-76c42180-8215-11e9-8d14-077fabe96183.png)

**Comment by pablotr9** [comment]
**UPDATE** 
HIPAA and NIST-800-53 dashboards have been updated and tested with Wazuh 3.10 for both Overview and Agents sections.
-Descriptions for NIST-800-53 requirements have been added.

An example of Overview -> NIST 800-53 Dashboard
![Screenshot from 2019-05-31 13-28-24](https://user-images.githubusercontent.com/35685689/58703261-61cbc780-83a8-11e9-90e2-baa29d82e5ab.png)

Currently working on adding HIPAA requirements description.

**Comment by pablotr9** [comment]
**Update**
It has been added new description for HIPAA requirements and NIST 800-53 requirements. https://github.com/wazuh/wazuh-splunk/commit/675d0739a0b4de7154004b86167d3ef89dfcf92a
There was an error with Nist-800-53 visualizations due to the use of underscores in its name, it has been fixed here: https://github.com/wazuh/wazuh-splunk/commit/13f70f80977186726a46e7014d37100eb601c6e9
Now we can filter our ruleset by HIPAA and NIST 800-53 requirements:https://github.com/wazuh/wazuh-splunk/commit/8fa46b005021aabf165d5d34918b567a224d81f6
![image](https://user-images.githubusercontent.com/35685689/58786626-4949f000-85e8-11e9-93c8-9b027488bd13.png)

**Comment by jesusgn90** [comment]
This visualization is wrong:

![image](https://user-images.githubusercontent.com/8860227/58944563-65819480-8782-11e9-8aea-a8bb2d61828c.png)

Please, change its _look & feel_, you can use https://github.com/wazuh/wazuh-kibana-app/issues/1448#issuecomment-496892011 as reference.

The requirements slider is a bit rough:

![image](https://user-images.githubusercontent.com/8860227/58944791-cc06b280-8782-11e9-99a3-ab5167429c65.png)

On the other hand, the issue doesn't show the full dashboard, add screenshot once finished. 

Thanks

**Comment by pablotr9** [comment]
**UPDATE**
Those requested improvements to HIPAA and NIST 800-53 dashboards have been added here: https://github.com/wazuh/wazuh-splunk/commit/d6b3e278a05de7a3c7042b740265dfba8cbac481
PCI DSS and GDPR dashboards have also been updated in order to maintain the proposed style.

Overview dashboards:
- PCI DSS
![overview-pci](https://user-images.githubusercontent.com/35685689/58952729-cca84480-8794-11e9-96c4-4f790892aaa5.png)
- GDPR
![gdpr-overview](https://user-images.githubusercontent.com/35685689/58952661-9ff42d00-8794-11e9-92a7-8bf5e19c54ae.png)
- HIPAA 
![hipaa-overview](https://user-images.githubusercontent.com/35685689/58952684-ada9b280-8794-11e9-89e9-67ed0f3a7a7a.png)
- NIST 800-53
![nist-overview](https://user-images.githubusercontent.com/35685689/58952693-b5695700-8794-11e9-808f-0496eba6f586.png)
  
   
AGENTS dashboards:
- PCI DSS
![pci-overview](https://user-images.githubusercontent.com/35685689/58952628-8b179980-8794-11e9-9fc2-f6fcec6a62e9.png)
- GDPR
![gdpr-agents](https://user-images.githubusercontent.com/35685689/58952743-da5dca00-8794-11e9-8f18-36194fc9a726.png)
- HIPAA 
![hipa-agents](https://user-images.githubusercontent.com/35685689/58952749-e053ab00-8794-11e9-8870-fb1b735f13f5.png)
- NIST 800-53
![nist-agents](https://user-images.githubusercontent.com/35685689/58952761-e77ab900-8794-11e9-8bfd-0177f77db385.png)

**Comment by jesusgn90** [comment]
This visualization is still wrong and it exists in more than one dashboard. This should be an aggregation and the right legend should show requirement names instead of "Count"

![image](https://user-images.githubusercontent.com/8860227/58956277-38db7600-879e-11e9-95a4-66461d6f9104.png)

A valid example:

![image](https://user-images.githubusercontent.com/8860227/58956412-940d6880-879e-11e9-8de6-0ab85a7d70c8.png)

This is not how we show the timestamp field:

![image](https://user-images.githubusercontent.com/8860227/58956437-a25b8480-879e-11e9-906c-50c95a504563.png)

Please use the grid properly:

![image](https://user-images.githubusercontent.com/8860227/58956517-c4ed9d80-879e-11e9-9f0d-45656c5cf65b.png)

Be consistent:

![image](https://user-images.githubusercontent.com/8860227/58956539-d6cf4080-879e-11e9-9843-fb018cecb587.png)

**Comment by pablotr9** [comment]
**UPDATE**
Grid are now used properly, text descriptions are consistent and the **_time** has been replaced.
I have encountered some problems renaming **_time**, the easiest way to do that was by simply renaming _time for a human-readable format as follows:
`(search query) | rename _time as "Time span"
`![Screenshot from 2019-06-06 10-37-26](https://user-images.githubusercontent.com/35685689/59019833-09357800-8849-11e9-94e4-a1688ab2fd5f.png)

Renaming **_time** forced Splunk to format _time value to milliseconds but we need a human-readable format for this value as well, this can be solved by formatting it again:
`(search query)| rename _time as Time | convert ctime(Time) `
![Screenshot from 2019-06-06 10-49-54](https://user-images.githubusercontent.com/35685689/59019857-1488a380-8849-11e9-825a-aa3e05e43539.png)
Once again, this date transformation (from milliseconds to dd/mm/yyyy HH:MM:SS) changed the user selected time range.
I finally achieved this by modifying all our chart classes so they now have one new optional param:
{customAxisTitleX : "Time span"}
This new param can be set to all our chart visualizations so we can set a custom axis X title without modifying any of the visualization data or time range as the next screenshot shows:
![image](https://user-images.githubusercontent.com/35685689/59020319-071fe900-884a-11e9-922d-4c126daae3e2.png)
